/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* This is used by the server - points to DIY project */

export const projectId = "oqjgvzaedlwarmyjlsoz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xamd2emFlZGx3YXJteWpsc296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxODYxMDYsImV4cCI6MjA3Nzc2MjEwNn0.GqxEM1JbbCcBj5m2sORBIvWX_JD5JrdYkkdidvp5Hzc"
